common:
  languages:
    en_US:
      progress: 100
      name: English
      author: null
    fr:
      progress: 100
      name: Français
      author: 'MichaelS, TomRh'
    id:
      progress: 99
      name: Bahasa Indonesia
      author: 'Zuhh, Lyden'
    tr:
      progress: 100
      name: Türkçe
      author: null
    es_ES:
      progress: 100
      name: Español
      author: TomRh
    pt_BR:
      progress: 100
      name: Português(BR)
      author: 'HydroXBR, Maxon, Bernard0'
    pl:
      progress: 14
      name: Polskie
      author: Kinga
dev:
  serverURL: 'http://localhost:3001'
  serverAPIURL: 'http://localhost:3001/BrainlyTools'
  shortenedLinkURL: 'http://localhost:3001/l'
  uploadedFilesURL: 'http://localhost:3001/files/uploaded/'
  env: development
production:
  serverURL: 'https://sahin.in'
  serverAPIURL: 'https://sahin.in/BrainlyTools'
  shortenedLinkURL: 'http://sahin.in/l'
  uploadedFilesURL: 'http://sahin.in/files/uploaded/'
  env: production
